-- UNION Logistics / 원료 주간 입고 계획
-- Supabase SQL Editor에서 한 번 실행하세요.
-- 주의: 아래 RLS 정책은 현재 프로그램에 로그인 기능이 없기 때문에
-- 브라우저에서 읽기/쓰기 모두 가능하도록 만든 프로토타입용 정책입니다.
-- 사내 실사용 전에는 Supabase Auth + 사용자별 RLS로 교체하는 것을 권장합니다.

create table if not exists public.materials (
  id bigint generated by default as identity primary key,
  team text not null check (team in ('team1','team2')),
  name text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.entries (
  id bigint generated by default as identity primary key,
  team text not null check (team in ('team1','team2')),
  week date not null,
  material text not null,
  day_index integer not null check (day_index between 0 and 5),
  amount integer not null check (amount >= 0),
  created_at timestamptz not null default now()
);

create index if not exists materials_team_sort_idx
  on public.materials(team, sort_order);

create index if not exists entries_team_week_idx
  on public.entries(team, week);

alter table public.materials enable row level security;
alter table public.entries enable row level security;

drop policy if exists "public read materials" on public.materials;
drop policy if exists "public insert materials" on public.materials;
drop policy if exists "public update materials" on public.materials;
drop policy if exists "public delete materials" on public.materials;

create policy "public read materials"
  on public.materials for select
  to anon, authenticated
  using (true);

create policy "public insert materials"
  on public.materials for insert
  to anon, authenticated
  with check (true);

create policy "public update materials"
  on public.materials for update
  to anon, authenticated
  using (true)
  with check (true);

create policy "public delete materials"
  on public.materials for delete
  to anon, authenticated
  using (true);

drop policy if exists "public read entries" on public.entries;
drop policy if exists "public insert entries" on public.entries;
drop policy if exists "public update entries" on public.entries;
drop policy if exists "public delete entries" on public.entries;

create policy "public read entries"
  on public.entries for select
  to anon, authenticated
  using (true);

create policy "public insert entries"
  on public.entries for insert
  to anon, authenticated
  with check (true);

create policy "public update entries"
  on public.entries for update
  to anon, authenticated
  using (true)
  with check (true);

create policy "public delete entries"
  on public.entries for delete
  to anon, authenticated
  using (true);

-- Supabase Realtime
alter publication supabase_realtime add table public.materials;
alter publication supabase_realtime add table public.entries;
